### ISSUE TITLE
A few questions so I can use my own data

### ISSUE THREAD

**Issue by hlalibe** [danaugrs/go-tsne#1]
Hi,

Installed everything and mnist2d works nicely out of Jupyter Notebook.
.png files are created in my folder and I can visualize the progression.

Now, I would really like to run the 2d on my images, a few questions:
- how do I transform my .png images to create the csv file like we see in mnist2500_X.csv ?
- my images are 533x800 pixels, is this too big ? the .png files for mnist2d were created in about 3 minutes on my PC
- my .png files are in color, do i need to convert them to black and white first ?
- do you have any legend for your charts ?

thanks

**Comment by danaugrs** [comment]
Hey, glad to hear it works nicely from a Jupyter Notebook. Are you using [gophernotes](https://github.com/gopherdata/gophernotes)?

Each row in `mnist2500_X.csv` is the unrolled version of a 28x28 MNIST digit image, with 784 black-and-white pixels - i.e. 784 dimensions. To create a similar file with your image data using Go you could write a subroutine to load your images using the [go standard image library](https://godoc.org/image) and unroll them into the rows of a csv file.

A 533x800 black-and-white image would have 426,400 values, which is ~544 times the size of an MNIST digit. And note that the MNIST digits aren't fed directly to t-SNE, they are [preprocessed with PCA first](https://github.com/danaugrs/go-tsne/blob/master/examples/mnist2d/mnist2d.go#L35-L39) in order to reduce the number of dimensions from 784 to 50 in `mnist2d` and to 100 in `mnist3d`. I recommend you do the same with your images i.e. drastically reduce the number of dimensions using PCA prior to running t-SNE.

You don't have to transform your color images to black-and-white, you just need to unroll them properly - i.e. unrolling a color image would give you 533x800x3=1,279,200 values. If PCA is too slow you can try scaling your images down and/or converting them to black-and-white and/or picking a smaller subset of images to work with.

Plotting is not part of this library. In the `mnist2d` example I used [gonum/plot](https://github.com/gonum/plot). See [here](https://github.com/gonum/plot/wiki/Example-plots) for examples of plots with legends.

**Comment by hlalibe** [comment]
Yes, I'm using gophernotes. I attach the notebook with your code, slightly re-arrange to make it work in this environment. (had to zip it in order to upload)

I will follow your advice and try it with a few of my pictures.

But just to be sure I understand what we see on the final set of 2d charts
- I suppose each color on your chart correspond to a specific digit in the mnist set, right ?
- But the system does not use these labels to cluster them, it's only grouping them by similarities, right ?
- The csv file with the labels is only used to put different colors on different digits, right ?


[mnist2d.ipynb.tar.gz](https://github.com/danaugrs/go-tsne/files/2493005/mnist2d.ipynb.tar.gz)

**Comment by danaugrs** [comment]
Hey, yes each point's shape+color corresponds to a particular digit class.
And that's right, the labels are not used by t-SNE (only the raw data is), the labels are just used for visualizing digits of different classes differently.
Thanks for sharing the notebook, I would love to see the final visualizations you produce based on your image data!
